import { atom } from 'recoil';

export const roomUser = atom<any>({
  key: 'roomUserList',
  default: [
    {
      peerIdx: 1,
      name: '김민수',
      socktId: null,
      videoStream: null,
      screenStream: null,
      video: false,
      sound: false,
      screen: false,
    },
    {
      peerIdx: 2,
      name: '김민수',
      socktId: null,
      videoStream: null,
      screenStream: null,
      video: false,
      sound: false,
      screen: false,
    },
    {
      peerIdx: 3,
      name: '김민수',
      socktId: null,
      videoStream: null,
      screenStream: null,
      video: false,
      sound: false,
      screen: false,
    },
    {
      peerIdx: 4,
      name: '김민수',
      socktId: null,
      videoStream: null,
      screenStream: null,
      video: false,
      sound: false,
      screen: false,
    },
    {
      peerIdx: 5,
      name: '김민수',
      socktId: null,
      videoStream: null,
      screenStream: null,
      video: false,
      sound: false,
      screen: false,
    },
    {
      peerIdx: 6,
      name: '김민수',
      socktId: null,
      videoStream: null,
      screenStream: null,
      video: false,
      sound: false,
      screen: false,
    },
  ],
});
