import type { NextPage } from 'next';
import Head from 'next/head';
import styled from 'styled-components';

const Home: NextPage = () => {
  return (
    <Wrapper>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        <h1>mogaco</h1>
      </Header>
      <Container>
        <h1>Home</h1>
      </Container>
    </Wrapper>
  );
};

export default Home;

const Wrapper = styled.div`
  width: 100%;
  height: 100%;
  background-color: #3aa5dd;
`;

const Header = styled.div`
  width: 100%;
  height: 48px;
  padding: 0 3rem;
`;

const Container = styled.div`
  width: 1440px;
  min-height: 100vh;
  margin: 0 auto;
`;
